### ISSUE TITLE
提到的例子看起来就是 《Rust In Action 》的例子

### ISSUE THREAD

**Issue by wangzhe3224** [rustcollege/rust-course#91]
提到的例子看起来就是 《Rust In Action 》的例子。如果真的要用，还是请联系作者或者注明引用，毕竟不是开源书。避免不必要的麻烦。：）

https://www.manning.com/books/rust-in-action

祝好

**Comment by sunface** [comment]
只是借用了灵感，这些例子还没在书中实现，难道连借用下灵感也不行了？您平时也这么高尚？完全不借用别人的好的想法？

真的，不必要，你太圣人了！

**Comment by sunface** [comment]
还有，您在知乎中也评论了吧？难为了，还删除了。。

**Comment by wangzhe3224** [comment]
你别误会。。我没别的意思，做开源不容易，但是省的惹麻烦。

**Comment by sunface** [comment]
好的，明白，还是谢谢你哈:)
